### ISSUE TITLE
app-iheart-radio will not load, player is completely broken

### ISSUE THREAD

**Issue by bpearson** [tiliado/nuvolaplayer#727]
### Basic information

- Your Linux distribution and its version: Pop!_OS 20.10

- Your desktop environment: Gnome (default installed)

 - Nuvola Runtime version: 4.21.0 (0-g96d9bdb)
   

 - The web app you use and its version: iHeartRadio 1.0.0 (0-gf93e83e)

### Describe the bug

Opening the app, shows a very broken page, with no controls.
DevTools shows up with this error...
index.m.js:1 Uncaught TypeError: Promise.allSettled is not a function
    at c (index.m.js:1)
    at Object.94847 (index.ts:94)
    at l (bootstrap:19)
    at Object.8601 (8882.www.js:1)
    at l (bootstrap:19)
    at Object.8594 (8882.www.js:1)
    at l (bootstrap:19)
    at Object.38672 (8882.www.js:1)
    at l (bootstrap:19)
    at Object.38046 (entry.www.js:1)

**Steps to reproduce the behavior**
1. Open app
2. View the brokeness?

**Expected behavior**

1. Open app
2.  Play the radio station.

**Debugging log**
[debug.txt](https://github.com/tiliado/nuvolaplayer/files/6347835/debug.txt)

**Screenshots**

Attach screenshots here: 
![Screenshot from 2021-04-21 13-30-30](https://user-images.githubusercontent.com/997686/115492783-cdbdbe80-a2a5-11eb-99e1-cb46e3978005.png)

**Additional context**

I thought it was something wrong with my system or the version of flathub, but other apps are working fine for me.
...

**Comment by fenryxo** [comment]
Hello @bpearson. Thanks for reporting your issue. Could you check whether the latest flatpak build with **iHeartRadio script 1.0.2 (2-g1c372a1)** fixes the problem for you? Thanks :-)

**Comment by bpearson** [comment]
Hi @fenryxo you champ! That fixed it. Thanks :)

**Comment by fenryxo** [comment]
Glad to hear that it works for you :-)
