### ISSUE TITLE
Can't build using vala 0.28.0

### ISSUE THREAD

**Issue by Aldarone** [tiliado/nuvolaplayer#102]
With vala 0.28.0, the build fails with this error message :

```
Compilation failed: 1 error(s), 0 warning(s)
/tmp/buildtmp/nuvolaplayer-git/src/nuvolaplayer-git/src/nuvolakit-runner/bindings/Binding.vala:74.2-74.15: error: destructor and parent symbol name do not match
        ~BaseBinding()
        ^^^^^^^^^^^^^^
```

Downgrading to vala 0.26.2 solves the issue.

**Comment by Celti** [comment]
fixed with the following patch: https://gist.github.com/Celti/60854f21bdb5e70847e7

**Comment by fenryxo** [comment]
Hello. Will apply the patch in early June.

**Comment by fenryxo** [comment]
Fixed in git master & 3.0.x branches. Thanks for your report and patch.
